server:
  port: 8761

spring:
  application:
    name: discovery-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: fals
    healthcheck:
      enabled: true
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 10000

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-details: always